### ISSUE TITLE
Verify that EC2 host cannot affect enclave's clock

### ISSUE THREAD

**Issue by NullHypothesis** [brave-experiments/nitriding#13]
According to https://github.com/aws/aws-nitro-enclaves-nsm-api/issues/15, an enclave's clock is automatically synced to the KVM clock. Still, we should probably verify that the EC2 host cannot affect the enclave's clock because that can cause various security problems.

**Comment by rillian** [comment]
Calling `sudo date --set 'DATESTRING'` on the host appears to have no effect on the output of `date` in the enclave. Any more sophisticated avenues to try?

I'm not sure how the test the the synchronization part other than leaving an enclave running for a few weeks and monitoring for clock drift.

**Comment by NullHypothesis** [comment]
> Calling `sudo date --set 'DATESTRING'` on the host appears to have no effect on the output of `date` in the enclave. Any more sophisticated avenues to try?

Thanks for testing this! I can't think of anything else to try.

> I'm not sure how to test the synchronization part other than leaving an enclave running for a few weeks and monitoring for clock drift.

I don't expect this to be a problem but let's revisit this conversation if it's going to be one. In the meanwhile, I'm going to close this ticket.
